// App shell per device family + screen stage wrapper.
import { ctx, ic, esc, btn, iconBtn, badge, chip, check, link, isSmall, isWide, isTV, kbd } from './html.mjs';
import { CLUSTERS, PAGES } from '../devices.mjs';

const logo = (dark) => `<a class="logo" href="${link('ana-sayfa')}" aria-label="arasta — ana sayfa"><span class="mark" aria-hidden="true">a</span><span class="word${dark ? ' on-dark' : ''}">arasta</span></a>`;
const searchBar = (o = {}) => `<form class="search${o.cat ? ' has-cat' : ''}" role="search" action="${link('arama')}">${o.cat ? `<label class="sr-only" for="hcat">Kategori</label><select id="hcat" class="search-cat"><option>Tümü</option><option>Tekstil</option><option>Makine</option><option>Gıda</option></select>` : ''}${ic('magnifying-glass', { cls: 'lead' })}<label class="sr-only" for="hq">Ürün, tedarikçi veya kategori ara</label><input id="hq" name="q" type="search" placeholder="${o.ph || 'Ürün, tedarikçi veya kategori ara'}" autocomplete="off">${o.kbd ? `<button type="button" class="kbd-btn" data-open="cmdk" aria-label="Komut paleti (Ctrl/⌘ K)">${kbd()}</button>` : ''}<button type="button" class="ai-btn" data-open="cmdk" aria-label="Akıllı arama">${ic('sparkle')}${o.aiLabel ? '<span>Akıllı arama</span>' : ''}</button><button type="button" class="cam-btn" aria-label="Görselle ara">${ic('camera')}</button></form>`;
const TABS = [['ana-sayfa', 'Keşfet', 'house'], ['kategoriler', 'Kategori', 'squares-four'], ['teklif-iste', 'Teklifler', 'file-text'], ['panel', 'Hesap', 'user']];
const tabFor = (slug) => ({ kategoriler: 'kategoriler', arama: 'kategoriler', 'teklif-iste': 'teklif-iste', teklifler: 'teklif-iste', panel: 'panel', mesajlar: 'panel', siparis: 'panel', giris: 'panel', kayit: 'panel', yardim: 'panel' }[slug] || 'ana-sayfa');

export function header(page) {
  const f = ctx.fam;
  if (f === 'tv') return `<header class="hdr hdr-tv" role="banner">${logo(true)}<nav class="tv-tabs" aria-label="Ana menü">${[['ana-sayfa', 'Keşfet'], ['kategoriler', 'Kategoriler'], ['flash', 'Flash Fırsatlar'], ['tedarikciler', 'Üreticiler'], ['teklifler', 'Tekliflerim']].map(([s, l]) => `<a href="${link(s)}" class="tv-tab"${s === page ? ' aria-current="page"' : ''} data-tv>${l}</a>`).join('')}</nav><div class="row gap16">${iconBtn('microphone', 'Sesli arama', 'tv', { attrs: ' data-tv' })}${iconBtn('user', 'Profil', 'tv', { attrs: ' data-tv' })}</div></header>`;
  if (f === 'phone') return `<header class="hdr hdr-phone" role="banner"><div class="row"><div class="row gap4 grow">${logo()}</div>${iconBtn('bell', 'Bildirimler, 3 yeni', 'ghost', { count: 3 })}${iconBtn('shopping-cart-simple', 'Sepet, 3 ürün', 'ghost', { count: 3, attrs: ` onclick="location.href='${link('sepet')}'"` })}</div>${searchBar({ ph: 'Ürün veya tedarikçi ara' })}</header>`;
  if (f === 'phoneL') return `<header class="hdr hdr-phoneL" role="banner">${searchBar({ ph: 'Ürün veya tedarikçi ara', aiLabel: true })}${iconBtn('bell', 'Bildirimler, 3 yeni', 'ghost', { count: 3 })}${iconBtn('chat-circle-dots', 'Mesajlar, 2 yeni', 'ghost', { count: 2 })}</header>`;
  if (f === 'tablet') return `<header class="hdr hdr-tablet" role="banner"><div class="row gap12">${logo()}${searchBar({})}${iconBtn('bell', 'Bildirimler, 3 yeni', 'ghost', { count: 3 })}${iconBtn('shopping-cart-simple', 'Sepet, 3 ürün', 'ghost', { count: 3 })}<a class="avatar" href="${link('panel')}" aria-label="Hesabım">DT</a></div>
<nav class="cat-tabs" aria-label="Kategoriler">${[['Tümü', 'squares-four', 1], ['Flash Fırsatlar', 'lightning'], ['Tekstil', 't-shirt'], ['Makine', 'factory'], ['Gıda', 'leaf'], ['Yapı', 'cube'], ['Ambalaj', 'package'], ['Elektrik', 'lightbulb'], ['Mobilya', 'couch']].map(([l, i, on]) => `<a href="${link(l === 'Flash Fırsatlar' ? 'flash' : 'kategoriler')}" class="cat-tab${on ? ' is-on' : ''}${l === 'Flash Fırsatlar' ? ' is-flash' : ''}">${ic(i, { s: 16 })}${l}</a>`).join('')}</nav></header>`;
  // tabletL / desktop / wide / ultra
  const util = f !== 'tabletL';
  return `<header class="hdr hdr-desk" role="banner">${util ? `<div class="hdr-util"><div class="container row gap24"><span class="row gap8 muted">${ic('seal-check', { s: 16, cls: 'ok' })}48.000 doğrulanmış üretici · Ticaret Güvencesi ile korunan ödeme</span><span class="grow"></span><a href="${link('tedarikci-ol')}">Tedarikçi olun</a><a href="${link('yardim')}">İhracat masası</a><a href="${link('yardim')}">Yardım</a><button type="button" class="locale">${ic('globe-simple', { s: 16 })}TR · ₺ TRY · EXW${ic('caret-down', { s: 16 })}</button></div></div>` : ''}
<div class="hdr-main"><div class="container row gap16">${logo()}<button type="button" class="btn btn-tertiary" data-open="mega" aria-expanded="false" aria-controls="mega">${ic('squares-four')}<span>Kategoriler</span></button>${searchBar({ cat: true, kbd: true, aiLabel: true })}${iconBtn('bell', 'Bildirimler, 3 yeni', 'ghost', { count: 3 })}${iconBtn('chat-circle-dots', 'Mesajlar, 2 yeni', 'ghost', { count: 2, attrs: ` onclick="location.href='${link('mesajlar')}'"` })}<a class="btn btn-secondary" href="${link('sepet')}">${ic('shopping-cart-simple')}<span>Sepet · 3</span></a><a class="acct" href="${link('panel')}"><span class="avatar" aria-hidden="true">DT</span><span class="acct-t"><b>Demir Tekstil</b><span>Alıcı · Kurumsal</span></span></a></div></div>
${f !== 'tabletL' ? `<nav class="hdr-nav" aria-label="Ana menü"><div class="container row gap24"><a class="flash" href="${link('flash')}">${ic('lightning')}Flash Fırsatlar</a><a href="${link('tedarikciler')}">Seçkin Üreticiler</a><a href="${link('arama')}">Yeni Gelenler</a><a href="${link('tedarikciler')}">Bölgesel Pazarlar</a><a href="${link('panel')}">Toplu Sipariş (CSV)</a><a href="${link('hakkimizda')}">Fuarlar</a><span class="grow"></span><span class="row gap8 muted">${ic('map-pin')}Teslimat: İzmir</span>${btn('Teklif İste', 'primary', { icon: 'file-text', href: link('teklif-iste') })}</div></nav>` : ''}${megaMenu()}</header>`;
}
export function bottomNav(page, custom) {
  if (ctx.fam !== 'phone') return '';
  if (custom) return `<div class="sticky-bar" role="region" aria-label="Sayfa eylemleri">${custom}</div>`;
  const cur = tabFor(page);
  return `<nav class="bnav" aria-label="Alt menü">${TABS.map(([s, l, i]) => `<a href="${link(s)}"${s === cur ? ' aria-current="page"' : ''}><span class="ind">${ic(i, { duo: s === cur })}</span>${l}</a>`).join('')}</nav>`;
}
export function rail(page) {
  if (ctx.fam !== 'phoneL') return '';
  const cur = tabFor(page);
  return `<nav class="rail" aria-label="Ana menü"><a class="mark-only" href="${link('ana-sayfa')}" aria-label="arasta ana sayfa"><span class="mark" aria-hidden="true">a</span></a>${[...TABS.slice(0, 3), ['sepet', 'Sepet', 'shopping-cart-simple'], TABS[3]].map(([s, l, i]) => `<a href="${link(s)}"${s === cur || s === page ? ' aria-current="page"' : ''}><span class="ind">${ic(i, { duo: s === cur })}</span>${l}</a>`).join('')}</nav>`;
}
export function footer() {
  if (isTV()) return `<div class="tv-hints" aria-hidden="true">${[['OK', 'Seç'], ['◀ ▶ ▲ ▼', 'Gezin'], ['Geri', 'Önceki ekran'], ['Mikrofon', 'Sesli ara']].map(([k, t]) => `<span><kbd>${k}</kbd>${t}</span>`).join('')}</div>`;
  const cols = [['Alıcılar', [['Teklif iste (RFQ)', 'teklif-iste'], ['Toplu sipariş (CSV)', 'panel'], ['Ticaret Güvencesi', 'guvence'], ['Numune talebi', 'urun']]], ['Tedarikçiler', [['Tedarikçi olun', 'tedarikci-ol'], ['Mağaza yönetimi', 'tedarikci-ol'], ['Reklam çözümleri', 'tedarikci-ol']]], ['Kurumsal', [['Hakkımızda', 'hakkimizda'], ['Kariyer', 'hakkimizda'], ['Sürdürülebilirlik', 'hakkimizda']]], ['Destek', [['Yardım merkezi', 'yardim'], ['Anlaşmazlık çözümü', 'guvence'], ['Erişilebilirlik beyanı', 'yardim'], ['Sistem durumu', 'durumlar']]]];
  return `<footer class="ftr" role="contentinfo"><div class="container"><div class="ftr-news"><div><h2>Flash etkinlikleri ve fiyat düşüşlerini ilk siz duyun</h2><p>Haftada en fazla 2 e-posta. İstediğiniz an ayrılabilirsiniz.</p></div><form class="row gap8" onsubmit="event.preventDefault();this.querySelector('button').textContent='Abone olundu';"><label class="sr-only" for="nl">E-posta</label><input id="nl" type="email" placeholder="ornek@firma.com.tr" autocomplete="email">${btn('Abone ol', 'onDark', { type: 'submit' })}</form></div>
${isSmall() ? cols.map(([h, ls]) => `<details class="ftr-acc"><summary>${h}${ic('caret-down')}</summary><ul>${ls.map(([t, s]) => `<li><a href="${link(s)}">${t}</a></li>`).join('')}</ul></details>`).join('') : `<div class="ftr-cols"><div>${logo(true)}<p>Türkiye’nin seçkin üreticilerini dünyayla buluşturan B2B pazar yeri.</p></div>${cols.map(([h, ls]) => `<div><h3>${h}</h3><ul>${ls.map(([t, s]) => `<li><a href="${link(s)}">${t}</a></li>`).join('')}</ul></div>`).join('')}</div>`}
<div class="ftr-legal"><span>© 2026 Arasta Teknoloji A.Ş. · ISO 27001 · PCI DSS</span><span class="grow"></span><a href="${link('yardim')}">KVKK</a><a href="${link('yardim')}">Çerez tercihleri</a><a href="${link('yardim')}">Koşullar</a></div></div></footer>`;
}
function megaMenu() {
  return `<div class="mega card" id="mega" hidden><div class="mega-sectors" role="list">${[['Tekstil & Hazır Giyim', 't-shirt', 1], ['Makine & Endüstri', 'factory'], ['Gıda & Tarım', 'leaf'], ['Yapı & Seramik', 'cube'], ['Ambalaj & Baskı', 'package'], ['Elektrik & Aydınlatma', 'lightbulb'], ['Mobilya & Ev', 'couch'], ['Kimya & Plastik', 'flask']].map(([t, i, on]) => `<a role="listitem" href="${link('kategoriler')}" class="${on ? 'is-on' : ''}">${ic(i, { duo: !!on })}<span>${t}</span>${on ? ic('caret-right', { s: 16 }) : ''}</a>`).join('')}</div>
<div class="mega-cols">${[['Örme kumaş', ['Penye', 'Ribana', 'İnterlok', 'Süprem']], ['Dokuma kumaş', ['Gabardin', 'Keten', 'Denim', 'Poplin']], ['Ev tekstili', ['Havlu', 'Nevresim', 'Perde']]].map(([h, ls]) => `<div><h3>${h}</h3><ul>${ls.map((x) => `<li><a href="${link('arama')}">${x}</a></li>`).join('')}</ul></div>`).join('')}</div>
<div class="mega-promo">${badge('Uyum %92', 'ai', 'sparkle')}<h3>Tekstilde AI tedarikçi eşleştirme</h3><p class="muted">İhtiyacınızı yazın; kapasite, sertifika ve teslim süresine göre sıralayalım.</p>${btn('Denemeye başla', 'tertiary', { icon: 'sparkle', href: link('teklif-iste') })}</div></div>`;
}
export function overlays() {
  return `<dialog class="cmdk" id="cmdk" aria-label="Komut paleti"><form method="dialog" class="cmdk-in"><div class="cmdk-q">${ic('magnifying-glass')}<label class="sr-only" for="cmdq">Ara veya komut yazın</label><input id="cmdq" value="penye kumaş denizli" autocomplete="off"><button class="kbd-close" value="close" aria-label="Kapat">Esc</button></div>
<div class="cmdk-g"><p class="over">Öneriler</p>${[['sparkle', 'AI: Denizli’den organik penye, 5.000 m, 30 gün', 'arama', 'Enter'], ['magnifying-glass', 'penye kumaş denizli — 1.204 ürün', 'arama'], ['storefront', 'Ege Tekstil A.Ş. — tedarikçi', 'magaza']].map(([i, t, s, k], n) => `<a class="cmdk-o${n === 0 ? ' is-active' : ''}" href="${link(s)}">${ic(i)}<span>${t}</span>${k ? `<kbd>${k}</kbd>` : ''}</a>`).join('')}</div>
<div class="cmdk-g"><p class="over">Eylemler</p>${[['file-text', 'Yeni teklif talebi oluştur', 'teklif-iste'], ['file-csv', 'CSV ile toplu sipariş yükle', 'panel'], ['arrows-left-right', 'Karşılaştırma listesini aç (3)', 'karsilastir']].map(([i, t, s]) => `<a class="cmdk-o" href="${link(s)}">${ic(i)}<span>${t}</span></a>`).join('')}</div>
<p class="cmdk-f">↑↓ gezin · Enter seç · Esc kapat</p></form></dialog>
<dialog class="sheet" id="filters" aria-labelledby="fsh"><form method="dialog"><div class="sheet-grip" aria-hidden="true"></div><div class="row between"><h2 id="fsh">Filtreler</h2><button class="icon-btn icon-btn-ghost" value="close" aria-label="Kapat">${ic('x')}</button></div>
<fieldset><legend>Tedarikçi</legend>${check('Doğrulanmış üretici', true)}${check('Ticaret Güvencesi', true)}${check('Yerinde denetimli', false)}</fieldset>
<fieldset><legend>Min. sipariş (MOQ)</legend><div class="row wrap gap8">${['≤ 100', '≤ 500', '≤ 1.000', 'Tümü'].map((t, i) => chip(t, { on: i === 1 })).join('')}</div></fieldset>
<div class="row gap12">${btn('Temizle', 'secondary', { attrs: ' value="close"' })}${btn('1.204 ürünü göster', 'primary', { cls: 'grow', attrs: ' value="close"' })}</div></form></dialog>
<div class="toast card" id="toast" role="status" hidden>${ic('check-circle', { cls: 'ok' })}<div><b>Eklendi</b><p class="muted">İşlem tamamlandı.</p></div></div>`;
}
export function compareTray() { if (!isWide()) return ''; return `<div class="ctray" role="region" aria-label="Karşılaştırma tepsisi"><b>Karşılaştır</b>${['t-shirt', 'package', 'couch'].map((i) => `<span class="slot">${ic(i, { duo: true, s: 28 })}</span>`).join('')}<span class="slot empty">${ic('plus')}</span><span class="grow"></span><span class="muted-inv">3 / 4 ürün</span>${btn('Karşılaştır', 'primary', { icon: 'arrows-left-right', href: link('karsilastir') })}${iconBtn('x', 'Karşılaştırmayı temizle', 'inv')}</div>`; }

// Complete document for one page on one screen
export function doc({ page, title, main, bottom, screen, clusters = CLUSTERS, live = false }) {
  const f = ctx.fam; const b = ctx.base;
  const pageList = PAGES.map((p) => `<option value="${link(p.slug)}"${p.slug === page ? ' selected' : ''}>${esc(p.title)}</option>`).join('');
  const screenList = clusters.flatMap((c) => c.screens.map((s) => `<option value="${b}${c.slug}/${s.id}/${page}.html"${screen && s.id === screen.id && c.slug === screen.cluster.slug ? ' selected' : ''}>${esc(c.title)} · ${esc(s.id)}</option>`)).join('');
  const bar = live ? '' : `<div class="devbar" role="navigation" aria-label="Ekran gezgini"><a class="devbar-home" href="${b}index.html">${ic('squares-four')}<span>Tüm ekranlar</span></a><span class="devbar-crumb"><a href="${b}${screen.cluster.slug}/index.html">${esc(screen.cluster.title)}</a> › <a href="${b}${screen.cluster.slug}/${screen.id}/index.html">${esc(screen.id)}</a></span>
<label class="sr-only" for="dv-s">Ekran</label><select id="dv-s" onchange="location.href=this.value">${screenList}</select><label class="sr-only" for="dv-p">Sayfa</label><select id="dv-p" onchange="location.href=this.value">${pageList}</select><span class="devbar-size">${screen.w}×${screen.h}</span><button type="button" id="dv-zoom" class="devbar-btn" aria-pressed="false">Sığdır</button><button type="button" id="dv-theme" class="devbar-btn" aria-label="Açık/koyu tema">${ic('moon', { s: 16 })}</button></div>`;
  const app = `<div class="app fam-${f}"${live ? '' : ` style="width:${screen.w}px;min-height:${screen.h}px"`}>${f === 'phoneL' ? rail(page) : ''}<div class="app-col"><a class="skip" href="#main">İçeriğe geç</a>${header(page)}<main id="main" tabindex="-1">${main}</main>${footer()}${compareTray()}${bottomNav(page, bottom)}</div>${overlays()}</div>`;
  return `<!doctype html><html lang="tr" data-fam="${f}"${screen ? ` data-screen="${screen.id}"` : ''}><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>${esc(title)} · ${screen ? esc(screen.cluster.title + ' ' + screen.id) + ' · ' : ''}Arasta</title><meta name="description" content="Arasta B2B pazar yeri — ${esc(title)}${screen ? ' — ' + esc(screen.label) : ''}">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600;700&family=Roboto+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="${b}assets/arasta.css"><link rel="icon" href="${b}assets/favicon.svg"></head><body class="${live ? 'live' : 'screen'}">${bar}<div class="stage" id="stage"${live ? '' : ` data-w="${screen.w}"`}>${app}</div><script src="${b}assets/app.js" defer></script></body></html>`;
}
